name: CI

on: [push]

env:
  RUBYOPT: -EUTF-8
  BUNDLE_PATH: vendor/bundle
  BUNDLE_APP_CONFIG: vendor/bundle
  RACK_ENV: production
jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[ci skip]')

    runs-on: ubuntu-latest
    container:
      image: ruby:2.7

    steps:
    - uses: actions/checkout@v2
    - name: cache bundler
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundler-${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          bundler-${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}
          bundler-${{ runner.os }}-
    - name: bundle install
      run: |
        gem install -N bundler
        bundle install --jobs 4 --retry 3 --without development
    - name: build
      run: bundle exec rake build
    - name: deploy
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build
